### ISSUE TITLE
[TASK] Relayer | Review and simplify setup/usage instructions

### ISSUE THREAD

**Issue by dutterbutter** [tangle-network/webb-docs#71]
## Overview

We want to make it as easy as possible for external users to run a relayer and support various networks. In an ideal state, users will download relayer binary, fetch relevant configuration files and will only have to update with their private keys to get started. 

We need to update the existing docs site to achieve the above flow. 

### Task Checklist

- [x] Add script to docs site to download and run relayer binary
- [x] Improve configuration fetching for immediate usage 
- [ ] Review existing documentation for the following sections to ensure its accuracy:
     - [ ] [Running with Docker](https://docs.webb.tools/docs/relayer/running-relayer/running-docker/)
     - [ ] [Running with Systemd](https://docs.webb.tools/docs/relayer/running-relayer/cloud-setup/)
     - [x] [Configuration Options](https://docs.webb.tools/docs/relayer/running-relayer/config-options/)
     - [ ] [Relayer API](https://docs.webb.tools/docs/relayer/running-relayer/relayer-api/)
